### PR TITLE
Bumps js deps

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

HOTT-<TODO>

### What?

I have added/removed/altered:

- [ ] Added foo in bar
- [ ] Removed baz

### Why?

I am doing this because:

-
-
-

### Have you? (optional)

- [ ] Reviewed view changes with stake holders
- [ ] Validated mobile responsive behaviour of view changes

### Deployment risks (optional)

- Makes changes to our complex routing setup that may affect apis to proxying to backend

### CODE REVIEW

**Review by jebw — CHANGES_REQUESTED** [review]
Specs are failing - do we actually want to be using the release candidate of webpacker though?

**Comment by willfish** [comment]
That was me debugging why some assets weren't loading

**Comment by jebw** [comment]
Ah - sorry - thought this PR was up for review

**Comment by willfish** [comment]
Ended up closing as have other fish to fry :fish: :cook:

**Pull request closed without merging**
