### PR TITLE
Fix additional code labels for XI and UK.

### PR DESCRIPTION
**Pull request by alexdesi**
### Jira link
https://transformuk.atlassian.net/browse/HOTT-1327

### What?
Fix additional code labels for XI and UK.

### CODE REVIEW

**Comment by alexdesi** [comment]
Before:
Screenshot 2022-02-17 at 15 49 27

After:
Screenshot 2022-02-17 at 15 45 04

**Review by jebw — APPROVED** [review]
LGTM

**Review by willfish — DISMISSED** [review]
We need to hide these

**Comment by willfish** [comment]
We should add the same to the document code step if this is what @mattlavis-transform wants for all of the steps with missing labels

**Comment by alexdesi** [comment]
@willfish I think you are right for the radio buttons, which already have a label for each item.
In that case I fixed the form and removed the explicit H1.

For the selectbox I added the label as discussed (all the other fields in other pages have already a label).

**Pull request merged**
